server:
  port: 10101
spring:
  application:
    name: sso-ssoReg
  redis:
    database: 0
    port: 6379
    host: 127.0.0.1
    password: 123456



eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: true
    ip-address: localhost
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:10010/eureka/
    enabled: true



