server:
  port: 10303
spring:
  application:
    name: sso-ssoapi

eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: true
    ip-address: localhost
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:10010/eureka/
    enabled: true